### ISSUE TITLE
Excess data in pain.008.001.02

### ISSUE THREAD

**Issue by aryzhenko** [php-sepa-xml/php-sepa-xml#10]
I've tried to use your package for generate SEPA files for ING bank in Netherlands. But validaion is fails because of excess data in header.
```xml
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.002.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.008.002.02 pain.008.002.02.xsd">
```
fails.
But next is ok:
```xml
<Document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02">

```

**Comment by israelromosen** [comment]
I've tried to use your package for generate SEPA files spanish bank, adding your modification, but I don't know if i'm doing correctly, because the labels id, OrgId, Othr and Id don't show.
Thanks.

**Comment by monofone** [comment]
@israelromosen I`m not sure how I could help you, if you extend your information about what you have done, it will possibly easier.

**Comment by monofone** [comment]
@rizhiy87 Which validation fails ? the one of your Bank or one of the unit tests which does the validation tests ?

**Comment by rizhiy87** [comment]
@monofone I've used this validation tool of ING bank:
https://www.ingsepa.com/our-help/additional-services/format-validation-tool/

**Comment by BenjaminPaap** [comment]
The original issue is solved with that last merged commit. You can use the parameter `withSchemaLocation` to disable the schema location attribute.

@israelromosen I think you problem is, that your bank is using an old pain format (pain.008.001.02) if you specify this when calling a method of the `TransferFileFacadeFactory` the missing fields you seem to need should be generated.

**Comment by barryvdh** [comment]
How can we set `withSchemaLocation`? It is available on the construct of the abstract, but you cannot set it on the actual Builders itself. See https://github.com/php-sepa-xml/php-sepa-xml/blob/8f9814bc7c97eda669e93848df3dcdb28ca7debb/lib/Digitick/Sepa/DomBuilder/CustomerDirectDebitTransferDomBuilder.php#L34-L37
