### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by schoettl** [php-sepa-xml/php-sepa-xml#103]
Hi, I'm glad that I discovered this project!

I'm just curious if this is a fork of https://github.com/dmitrirussu/php-sepa-xml-generator (or vice versa)?

Or is it pure coincidence that both are written in PHP?

Which one is to prefer?

Is there already something like a open source (command line) tool `csv2sepa` that converts CSV files to SEPA XML credit transfers? That would be very helpful. I'd create one, if nothing exists.

PS: I plan to test the output XML with [Hibiscus](https://www.willuhn.de/products/hibiscus/) – if successful, we can add it to the list of supporting banks/software.

**Comment by monofone** [comment]
Hey,

no they are not connected. Interesting that you use Hibiscus as connection to the bank.

I don't n know about a tool like this but haven't looked for one.

Which one to prefer is hard to say, For sure I would recommend this one but I never tried the other one so I can't judge about it.

Hope this helps so far, if there are any questions don't hesitate to ask.
