### ISSUE TITLE
PaymentInformation::getLocalInstrumentCode() must be of the type int or null, string returned

### ISSUE THREAD

**Issue by ericsala** [php-sepa-xml/php-sepa-xml#105]
There is a problem here: 

`$directDebit->addPaymentInfo('firstPayment', array(
            ...
            'localInstrumentCode'   => 'B2B' <--
        ));`

Is there any other option to create B2B ?
Thank you!

**Comment by monofone** [comment]
Hey, can you mention the version you used

PHP:
php-sepa-xml:

Thanks

**Comment by ericsala** [comment]
Ok! 
PHP: "7.4.8"
php-sepa-xml: "dev-master"

**Comment by monofone** [comment]
yes, that was broken somehow, thank you for flying with php-sepa-xml and opening an issue about this. It is fixed now in the master. I will bring out a new RC for this.
