### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by VincentLanglet** [php-sepa-xml/php-sepa-xml#110]
Hi @monofone,

Any visibility about the official 2.0 release ?
What is missing ? Can I/we help ?

**Comment by monofone** [comment]
HI @VincentLanglet 

thanks for reaching out again, I'm just uncertain about the release, that's all. If you give the OK for the I'll will happily release the first 2.0.

Stay safe, stay healthy - 

monofone

**Comment by VincentLanglet** [comment]
@monofone I don't use every feature, but my projet works with the 2.0-rc2 release. So let's try a 2.0 ! :) 

Stay safe too

**Comment by monofone** [comment]
I've done it !
