### ISSUE TITLE
batchBooking in credit transfers

### ISSUE THREAD

**Issue by PDFCoder** [php-sepa-xml/php-sepa-xml#115]
A very useful and good working php class do you provide here, thank you! We just used it successfully with StarMoney Professional and Commerzbank.

During our implementation of the code we found out that credit transfers don't take account of the "batchBooking" parameter – which is also useful here, not only for direct debits.

To fix this we added in \TransferFile\Facade\CustomerCreditFacade in method addPaymentInfo:

```
if (isset($paymentInformation['batchBooking'])) {
            $payment->setBatchBooking($paymentInformation['batchBooking']);
        }
```

Would you add this in an upcoming version of the class?

**Comment by BenjaminPaap** [comment]
Feel free to contribute your solution to this repository with a PR. We will review and merge if applicable.
