### ISSUE TITLE
Problem with float amount

### ISSUE THREAD

**Issue by mabjavaid** [php-sepa-xml/php-sepa-xml#117]
In `Digitick\Sepa\TransferInformation\BaseTransferInformation` class `amount` is type hinted as `Int` in `construct` method, when we pass a floating value, it ignore all after `.`. imagen we have to charge `1.99 EUR` and end up creating SEPA for just `1 EUR`.

**Comment by monofone** [comment]
you have to pass the value in cent like 199 for 1.99€

**Comment by mabjavaid** [comment]
@monofone thank you for quick response, is there any documentation that we can use to avoid such things :)

**Comment by monofone** [comment]
Well, it seems this is not mentioned somewhere. Don't hesitate to create a MR with additions to the documentation.
