### ISSUE TITLE
Credit vs Debit

### ISSUE THREAD

**Issue by mmethner** [php-sepa-xml/php-sepa-xml#119]
Hi,

I may have a silly question, but since I am not working the bank industry I want to make sure to understand things right.
I use TransferFileFacadeFactory::createDirectDebit() to create an xml export file to a german bank for sepa direct debit, which means, the bank will debit different bank accounts according to my instructions. 

Is it right, that the opposit of a direct depit is credit transfer, which I can handle with TransferFileFacadeFactory::createCustomerCredit()? What I need to do is to instruct my bank to transfer a certain amount of money back to the bank account of my customers, e.g., when I needed to cancell something and the customer did made a prepayment. Am I right?

Thanks for your support
Mathias

**Comment by monofone** [comment]
yes.
