### ISSUE TITLE
Referenced XSD version should be updated to 008.003.02 for direct debit

### ISSUE THREAD

**Issue by reikjarloekl** [php-sepa-xml/php-sepa-xml#12]
Changes from 008.002.02 to 008.003.03 are: support for Othr/NOTPROVIDED for the financian institute id (DD without BIC) and COR1 as the local instrument. Since both elements are provided, the referenced XSD version should be updated to 008.003.02.

**Comment by monofone** [comment]
Hey @reikjarloekl do you mean in the constructor of `CustomerDirectDebitTransferDomBuilder` ?

**Comment by reikjarloekl** [comment]
Yes, file format now conforms to .03, so this should be the default format.

**Comment by monofone** [comment]
As this would be a breaking change if someone relies on this default value I prefer to not change it at the moment. If you need another format there is the option to override the default.
