### ISSUE TITLE
Override SEPA-Xml bundle

### ISSUE THREAD

**Issue by aghar-saif-eddine** [php-sepa-xml/php-sepa-xml#125]
I am using sepa-XM to generate my XML file. I want to add some fields to my XML. So my question is can I override this bundle? and if I can ,are there any examples.
Thanks.

**Comment by monofone** [comment]
Hi @aghar-saif-eddine,

I don't have examples lying around, but the pattern used to build the XML is the so called [Visitor Pattern](https://en.wikipedia.org/wiki/Visitor_pattern) you can extend the visitors and let them do additional work.

[Here](https://github.com/php-sepa-xml/php-sepa-xml/blob/master/src/DomBuilder/DomBuilderFactory.php) is the entry point where the Visitor is created (`CustomerCreditTransferDomBuilder`) and if you extend this one an pass this to the `TransferFile` you will be able to generate a different output.

Hope this helps. And if you succeed it would be great to get a Pull Request with a description about how to do this in the Readme ;-)

Regards monofone
