### ISSUE TITLE
<nboftxs> and <CtrlSum> empty

### ISSUE THREAD

**Issue by tholag** [php-sepa-xml/php-sepa-xml#126]
I followed the doc, xml is valid and filled with transfers, but the `<nboftxs>` (Number of transfers) and `<CtrlSum>` (sum of transfers) in the Group header remain at 0,00. Seem like I missed a call to update `<GrpHdr>`? Any hints?

**Comment by tholag** [comment]
Found the issue: `addPaymentInformation` needs to be called after adding transfers, as adding transfers does not trigger an update of the group headers.

**Comment by monofone** [comment]
Seems to be lacking documentation, any possibilities to update the Readme ? would appreciate any PR for this  :-)
