### ISSUE TITLE
pain.008.002.02.xsd

### ISSUE THREAD

**Issue by philipus** [php-sepa-xml/php-sepa-xml#127]
sorry asking that stupid question but from where you got the file "pain.008.002.02.xsd"
on iso20022 webpage I can only find pain.008.001.xx.xsd schemas.

In fact I have the problem with missing annotations in several xsd file from iso20022 webpage.

Any thoughts on this?!

**Comment by monofone** [comment]
Probably @VincentLanglet can help here as he was the one committing those ?

**Comment by VincentLanglet** [comment]
I didn't commit those file, I just moved them.
Sorry, I know nothing about those.
