### ISSUE TITLE
$customerCredit->addTransfer : PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by louisjeck** [php-sepa-xml/php-sepa-xml#130]
Hello,
I'm getting this warning when following the `Sample Usage CreditTransfer with Factory` example on `pain.001.001.03`.

```PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/digitick/sepa-xml/src/DomBuilder/CustomerCreditTransferDomBuilder.php on line 178```

Seems to be because I don't pass any `creditorReference` since I'm using `remittanceInformation`

**Comment by ghuisman19** [comment]
Add creditorReference to the addTransfer variables and your problem is fixed.

**Comment by markusramsak** [comment]
> remittanceInformation

this is not the solution because remittanceInformation won't be set if creditorReference is not null
and if you try 'creditorReference' => '' then the creditorReference AND remittanceInformation will be empty in the file
I proposed two pull requests to solve the core issue

**Comment by monofone** [comment]
Thanks for your contributions, I merged them, will create a patch release for this.
