### ISSUE TITLE
Install in Magento 2 App

### ISSUE THREAD

**Issue by inmediape** [php-sepa-xml/php-sepa-xml#140]
We would like to install it in Magento 2.
We installed the package with

composer require digitick/sepa-xml:dev-master

In our class we have included

use Digitick\Sepa\TransferFile\Factory\TransferFileFacadeFactory;

we ran

php bin/magento setup:di:compile 

and got no errors.

When we call up our class we get the error instead

Class Digitick\Sepa\TransferFile\Factory\TransferFileFacadeFactory does not exist

Is it an Autoloader problem?
How can we solve?

**Comment by monofone** [comment]
Hey,

your message is lacking some informations, what PHP version, have you turned on dev mode for Magento, did you took a look into the compiled autoload file created by composer, etc. 

As this is not a Magento package I would suggest to dig deeper into the Magento mechanims.

Regards
