### ISSUE TITLE
regarding the license

### ISSUE THREAD

**Issue by adirkuhn** [php-sepa-xml/php-sepa-xml#141]
Hello, I was wondering if there is a possibility to change the LGPL license to one less restrictive like MIT,
most companies run away from GPL/LGPL.

This is my situation right now I want to include this library in the company project but the legal department is blocking doing so due to the restrictions of the license.

**Comment by monofone** [comment]
Hi, first of all I must admit that I had no clue that this lib is licensed under LGPL. Second I'm in no way a licence expert. But as I know If I would like to change the Licence this has to be acknowledged by the people who contributed to the lib.

And at least it's LGPL so you don't need to apply the same licence to your software you only need to publish changes to this lib if you did some as I understand it.

If you have more input on this don't hesitate to share it here.

**Comment by monofone** [comment]
I do not mean upcoming contributors, I meant the past contributions already done. Those are done under the LGPL and I do not know if I can just change the license now. If it is possible to ask this question to your legal Departement I would appreciate if you share this here.

**Comment by adirkuhn** [comment]
Will be no problem to change if the contributors agree to the change.

Mozilla did something similar [relicensing-faq](https://www-archive.mozilla.org/mpl/relicensing-faq)

Also Dolphin emulator [relicensing-dolphin](https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/)

> Despite our best efforts, contacting every single member of Dolphin was something that simply isn't possible. Over the past 8 years of open source development, Dolphin has accumulated over 200 contributors often registering with only a username and an email with nothing else. Out of all those, we managed to contact all or take care of the code of all but 10 of those developers. Considering that many of those accounts are now dead and the people seemingly vanished from the Internet, finding the rest is akin to squeezing blood out of a stone.

> That's when research provided us some much needed relief when it seemed as though relicensing was an impossibility. In 2003, Free Software lawyers consulted for [Mozilla's relicensing project](http://blogs.fsfe.org/ciaran/?p=58) and stated that relicensing with the permission of just 95% of contributors was fine, as long as there were no objections in the remaining 5%.

so if at least 95% of the contributors agree it's fine to change the license.

**Comment by adirkuhn** [comment]
Do you think that is feasible?
