### ISSUE TITLE
Feature Request: Strong types for values in the API

### ISSUE THREAD

**Issue by NexAdn** [php-sepa-xml/php-sepa-xml#150]
### The Problem

This library currently use types like `string` or `int` to represent objects like IBANs, BICs and especially money amounts.
For the first two this is not as critical, but especially when dealing with integer amounts, it can be dangerous to use plain integer types (e.g. consumers of the API having to remember to convert their float Euros to integer Cents).

### The Solution

Using a strong integer type (e.g. some `class EuroCent`) which can be created from various representations and converted internally to the one this library uses internally might be a good addition to the API (for backwards compatibility, the plain integer parameters can stay, of course). With the new interface, consumers have to be more aware of the unit their amount is in and they don't have to take care of converting it to the proper unit.

### Example:

This code can easily cause bugs if the developer forgets the unit the amount is in (especially if it changes during version bumps of the library):

```php
$credit = TransferFileFacadeFactory::createCustomerCredit($msg_id, $debtor_name);
// ...
$credit->addTransfer($msg_id, [
    'currency' => 'EUR',
    'amount' => 2000, // Is this Cents or Euros?
    // ...
]);
```

Instead, having strong types (I present a few variations here as examples) allows the consumer of the library to completely ignore the representation which is internally used in the library, since the strong integer type(s) can be designed to accept any popular representation of the money amount and convert into any needed representation.

```php
$credit = TransferFileFacadeFactory::createCustomerCredit($msg_id, $debtor_name);
// ...
$credit->addTransfer($msg_id, [
    'currency' => 'EUR',
    'amount' => new EuroCent(20, 00), // We now have 20 Euros and 00 Cents
    // ...
]);
$credit->addTransfer($msg_id, [
    'currency' => 'EUR',
    'amount' => new Euro(20), // We now have 20 Euros
    // ...
]);
$credit->addTransfer($msg_id, [
    'currency' => 'EUR',
    'amount' => new Cent(2000), // We now have 20 Euros, represented as Cents
    // ...
]);
```

The main issues with this approach I see are:

* Consumers need to explicitly create a new object of the desired type
* The library might need to decide on a good name for the new type which is independent of the currency used (I didn't have a good idea for a name yet, so I stuck with `EuroCent` for now)

**Comment by BorislavSabev** [comment]
@NexAdn your suggestion is great however there is one major problem with it. :
Introducing typed objects (that are essentially Value Objects) will increase the memory footprint by a lot. 


Using basic types such as `string` and `int` is a design choice - the library aims to generate ISO20022 XML files, not to validate the user's input data. While I agree that such quality of life improvements could better code that is calling library I don't support adding this to the lib at the moment. 

There are other problems with your proposal as well, some of which you correctly point out. Overall this library aims to follow the KISS philosophy.
