### ISSUE TITLE
Question about characters

### ISSUE THREAD

**Issue by allphat** [php-sepa-xml/php-sepa-xml#154]
Does anybody know if Cyrillic characters are allowed in a SEPA xml file?

I have a case where the customer name becomes empty after the call to sanitizestring.

Example: "ЮРИЙ"

returns an empty string.

**Comment by monofone** [comment]
the closest to this question I found was https://www.europeanpaymentscouncil.eu/document-library/guidance-documents/sepa-requirements-extended-character-set-unicode-subset-best.

TLDR; no

**Comment by BorislavSabev** [comment]
@allphat no you need to convert to the sepa extended character set. :)
