### ISSUE TITLE
Confirm that is working in Spain with BBVA

### ISSUE THREAD

**Issue by scramatte** [php-sepa-xml/php-sepa-xml#155]
Hi,

This library has been tested in Spain with BBVA bank 
For credit you must use pain.001.001.03

Hope that helps

Regards

**Comment by BorislavSabev** [comment]
Thank you for the information we will keep it in the archive.
For anyone's future sake please not that SEPA XMLs (ISO20022) are an inter-bank communications standard that should would with any bank part of the SEPA network. However different banks handle processes differently internally - for e.g. one bank may and will handle rejects in a different matter than the next though the inbound and outbound communication will remain based on the SEPA standard.
