### ISSUE TITLE
Feature Request: Support for pain.002.001.03 and pain.007.001.02

### ISSUE THREAD

**Issue by scramatte** [php-sepa-xml/php-sepa-xml#156]
Hello,

Can you add support for pain.002.001.03 and pain.007.001.02
These pain are tto allow return file parsing and Direct Debit Reversion

This guy do it  but modify namespaces  and don't make any PR
https://github.com/Gemabit/php-sepa-xml

Moreover it looks that is not maintained anymore

Regards

**Comment by BorislavSabev** [comment]
@scramatte you can submit a PR and we'd be happy to check it and test it.

**Comment by BorislavSabev** [comment]
Closing this issue as there is no comment from the author and no PR submitted.
