### ISSUE TITLE
Disparition PstlAdr dans le xml

### ISSUE THREAD

**Issue by Filantsoa** [php-sepa-xml/php-sepa-xml#166]
<PstlAdr>
<Ctry>GE</Ctry>
<AdrLine>75 Saburtalo District</AdrLine>
<AdrLine> City</AdrLine>
</PstlAdr>

**Comment by monofone** [comment]
Hey @Filantsoa, do you mind providing a little more context and probably describe in english what is happening ?

Translation told me "PstlAdr disappears from xml" I think PstlAddr is removed if empty. Please provide some code where you experience the vanishing of the PstlAddr node.

**Comment by BorislavSabev** [comment]
Closing this issue as there is no communication from the author

**Comment by BorislavSabev** [comment]
Closing this issue as there is no communication from the athor
