### ISSUE TITLE
dueDate to transfers / directCredit

### ISSUE THREAD

**Issue by seem2810** [php-sepa-xml/php-sepa-xml#167]
Hi,

is it possible to set ReqdExctnDt for each transfer?
I've a file with 10 transfers and want to time each for it.

https://github.com/php-sepa-xml/php-sepa-xml/pull/74

**Comment by BorislavSabev** [comment]
Hello @seem2810 is that in the standard? Can you reference it in the docs for ISO20022?

**Comment by BorislavSabev** [comment]
In the standard I don't see this being possible except on the Payment Information level. Thus it is not possible for single transfers or I cannot find a reference to that in the standard's documentation.

You can create 1 file with 1- Payment Information objects in it and set ReqdExctnDt on each `PmntInf` object separately
