### ISSUE TITLE
Refactor Documentation

### ISSUE THREAD

**Issue by monofone** [php-sepa-xml/php-sepa-xml#21]
@BenjaminPaap what do you think about refactoring the documentation into separate files for debit and credit and move them into their own folder (doc) as I think the README becomes very cluttered.

**Comment by BenjaminPaap** [comment]
I totally agree with that and am fine with a doc folder. If you want I can split the readme and commit that tomorrow or on the weekend

**Comment by BenjaminPaap** [comment]
Fixed with #22
