### ISSUE TITLE
CustomerCreditFacade missing from current stable

### ISSUE THREAD

**Issue by synaris** [php-sepa-xml/php-sepa-xml#25]
Hi guys,

I was just playing around with your project and noticed that the CustomerCreditFacade class appears to be missing from the sources tagged 1.0.0 as well as 1.1.0 and therefore the current stable version. Am I missing something here?

I'm going to use the dev-master for now but an update would be nice.

Thanks,
Julia

**Comment by xabbuh** [comment]
This was only added recently in #16 as a fix for #14 and there was no release after that PR was merged.

**Comment by monofone** [comment]
created new release
