### ISSUE TITLE
Support for pain.001.003.03?

### ISSUE THREAD

**Issue by xabbuh** [php-sepa-xml/php-sepa-xml#27]
It seems that the bank of one of our customers doesn't support pain.001.002.03 for credit transfers anymore and requires us to use pain.001.003.03. Did you already make some plans to support this standard? Or are you open to a pull request adding support for that format (admittedly I don't know yet what are the conrecete differences between both formats though)?

**Comment by monofone** [comment]
Sure we are open to pull requests, it would be nice if you can name the bank as we like to start a collection of banks and their supported pain formats so anyone just needs to take a look to know which format to use.

By the way, can you tell which gateway software you are using ?

**Comment by monofone** [comment]
just for reference purpose http://www.ebics.de/fileadmin/unsecured/anlage3/anlage3_pain001/pain_schema/pain.001.003.03.xsd

**Comment by xabbuh** [comment]
Thanks, I'll look into it and will ask our customer for the other information.

**Comment by BenjaminPaap** [comment]
@xabbuh maybe a little late but as far as I can see, the generated xml validates against pain.001.003.03 with this test: https://github.com/php-sepa-xml/php-sepa-xml/blob/1bd23d6732b552876abfab2123f4a6c1eeaf54c2/tests/CustomerCreditValidationTest.php#L34-L34

**Comment by xabbuh** [comment]
@BenjaminPaap No, it's not too late. :) I didn't have time to look into this yet.

**Comment by monofone** [comment]
@xabbuh any updates on the used gateway software ?

**Comment by xabbuh** [comment]
@BenjaminPaap @monofone Turned out there was some communication issues between the customer and their bank. As far as I understood them they used the bank's web interface (sadly I don't know the name of the bank).

**Comment by monofone** [comment]
@xabbuh according to the test this format is also covered and can be used by mentioning the format in the DomBuilder constructor
