### ISSUE TITLE
No luck getting diaeresis/trema in the XML

### ISSUE THREAD

**Issue by TisLars** [php-sepa-xml/php-sepa-xml#30]
In my current data I have a few names with special characters, like 'Fränzel'.

The names were not printed correctly after generating the SEPA XML file. After trying several encoding methods, it still did not come out correct.
Right now I noticed the `sanitizeString($inputString)` function in the `StringHelper` class. This function changes the special characters in my data. Why is this function present? Is it required?

How can I get the names with special characters (Fränzel) correct in the XML output?

**Comment by monofone** [comment]
It is not allowed to use special characters in the SEPA files

**Comment by BenjaminPaap** [comment]
Closing this as @monofone is completely right that special characters are not allowed in SEPA files. That `sanitizeString` method replaces german umlauts with their corresponding ascii representation. 'ä' will be replaced with 'ae' and so on.
