### ISSUE TITLE
Is the BIC required?

### ISSUE THREAD

**Issue by amenk** [php-sepa-xml/php-sepa-xml#32]
The library required the BIC field, otherwise it throws an error.

Is the BIC field required by the PAIN standard? Or can it be basically omitted?

**Comment by monofone** [comment]
Since 01.01.2016 in germany IBAN only is poossible. But you are right their are some issues with the library concerning the IBAN only implementation.

**Comment by amenk** [comment]
shall I patch that and make PR ? I think it is (for my use case) only two lines

**Comment by BorislavSabev** [comment]
@amenk the library doesn't support different versions if the pain standards. So I maybe this should be left in. A lot of banks and intermediaries require the BIC to be set and will reject the transfers.

**Comment by amenk** [comment]
I finally foud that it is working using "urn:iso:std:iso:20022:tech:xsd:pain.008.003.02"

What do you mean the library does not support different versions? But can't I specify it?

**Comment by amenk** [comment]
I simply have to use

    $directDebit = TransferFileFacadeFactory::createDirectDebit($msgId, $accountOwner, 'pain.008.003.02');

**Comment by amenk** [comment]
We could now - in the factory - check the PAIN version and then enforce the BIC or not. It this worth the effort?

**Comment by BorislavSabev** [comment]
@amenk you can specify the standard string yes, but the XML file builder is one and the same and if there are new/removed/changed fields in the next/previous version you're trying to use you could end up with different issues.

**Comment by amenk** [comment]
so can we merge as is?

**Comment by amenk** [comment]
can we merge?

**Comment by monofone** [comment]
In #34 is a good  starting point for creating the step to not need the BIC anymore but there are still missing some parts and a proper test for this case. If someone can improve this PR I will gladly accept a new PR but as @BorislavSabev stated it is not enough to only catch this in the facade.

**Comment by amenk** [comment]
https://github.com/php-sepa-xml/php-sepa-xml/pull/33 works fine for me as long as I specify the right PAIN  version ... (but I did not update the unit tests) but I am also fine to go with #34 ...

**Comment by amenk** [comment]
Any news on this? 
BTW: We experienced sometimes issues with Austrian Banks when exporting without BICs .. still try to clarify this with the Ban

**Comment by amenk** [comment]
*bump*

**Comment by monofone** [comment]
I think this is now fixed ...
