### ISSUE TITLE
How to set <ReqdColltnDt>

### ISSUE THREAD

**Issue by TisLars** [php-sepa-xml/php-sepa-xml#35]
The ReqdColltnDt information has to be set 6 days in the future by SEPA conform, some cases 3 days.

How can we change the date? Right now it is by default the current day.

**Comment by monofone** [comment]
Hey, you can set this by applying your date to the `dueDate` in the `PaymentInformation::setDueDate`. Or by using the facade 
```
CustomerDirectDebitFacade::addPaymentInfo('myPayment', [
  dueDate => MyDateTimeObject,
  ...
])
```
