### ISSUE TITLE
BtchBookg element

### ISSUE THREAD

**Issue by aquadictus** [php-sepa-xml/php-sepa-xml#36]
The BtchBookg element requires an int representation of a boolean so 1 or 0.
I'm using the $payment->setBatchBooking(0); to set the value.

When I set it to 1, I get the full element.
<BtchBookg>1</BtchBookg>

When I set it to 0 it will only add an empty element.
<BtchBookg/>

The bank (NL rabobank) requires the element to be filled, otherwise the file will not be accepted. I can work around it yet it would be usefull if it would add the full element regardless of contents.

**Comment by monofone** [comment]
Yes, you are right, this is not as expected, can you test the Pull request ?

**Comment by aquadictus** [comment]
This is working perfectly now thanks.
