### ISSUE TITLE
Filter out characters like _

### ISSUE THREAD

**Issue by amenk** [php-sepa-xml/php-sepa-xml#43]
santitizeString does not really what the name promisses 
https://github.com/php-sepa-xml/php-sepa-xml/blob/master/lib/Digitick/Sepa/Util/StringHelper.php#L31

It just transliterates (which might be easier via iconv).

But essentially it should filter out the remaining "bad-chars"?

**Comment by amenk** [comment]
$mapped = strtr($inputString, $map);
        $sanitized = preg_replace('/[^A-Za-z0-9:?,\-(+.) ]/', ' ', $mapped);

        return $sanitized;

**Comment by amenk** [comment]
shall I make a PR?

**Comment by monofone** [comment]
Yes you can make a PR for this, are you sure about the characters ? is a \ allowed in remittenceInformation or similar ?

**Comment by amenk** [comment]
\ is escaping the minus - the minus is allowed :-)
I have the list from formatpruefer.de

>	Warnung Unzulässiges Zeichen "_" gefunden. Kreditinstitute können das Zeichen ersetzen oder      
> die Datei zurückweisen. Erlaubt sind Ziffern, Groß- und Kleinbuchstaben sowie ':?,- (+.)/

**Comment by BorislavSabev** [comment]
Hello I just wanted to add some information from my experience with ISO20022/SEPA. 
While the standard is UTF-8 based certain fields need to include only the basic character set.

Here is a [document describing this basic set](http://www.sepahungary.hu/uploads/files/EPC217-08%20Best%20Practices%20-SEPA%20Requirements%20for%20Character%20Set.pdf) from the EPC.

I am pretty sure that the need for this "Basic Character Set" was to satisfy interoperability with legacy (bank) systems. Some fields that require this: EndToEndId, debitorName, creditorName, originName, creditorId...

I just searched for this in [iso20022.org Message Archieve](https://www.iso20022.org/message_archive.page) and couldn't find the official standard reference I used back then. The EPC doc and my code example should be mostly sufficient.


As this repo was originally forked from Digitick/php-sepa-xml and I had to add some chars manually in `sanitizeString()` there I am not sure all those are covered here. Here is my list of chars and their transliteration:

```
$searches = [
    'Ä', 'Ö', 'Ü', 'ä', 'ö', 'ü', 'ß','Ĉ','ĉ',
    'Ĕ','ĕ','È','è','É','é','Ġ','ġ','Ŝ','ŝ',
    'À','à','Á','á','Ò','ò','Ó','ó','Ô','ô',
    'Ù','ù','Ú','ú','Û','û','Ã','ã','Ç','ç',
    'Ê','ê','Ë','ë','Ï','ï'
];
$replacements = [
    'Ae', 'Oe', 'Ue', 'ae', 'oe', 'ue', 'ss','C','c',
    'E','e','E','e','E','e','G','g','S','s',
    'A','a','A','a','O','o','O','o','O','o',
    'U','u','U','u','U','u','A','a','C','c',
    'E','e','E','e','I','i'
];
```

I am willing to review the PR and see if all chars are covered. Hope this helped.

**Comment by monofone** [comment]
@BorislavSabev sorry I didn't checked the issue before merging the pr #44 if there are any characters missing feel free to add an additional pull request.

**Comment by BorislavSabev** [comment]
@monofone  I will review it and make a PR is necessary.

**Comment by BorislavSabev** [comment]
@monofone I created PR #48.
