### ISSUE TITLE
BIC optional

### ISSUE THREAD

**Issue by Abdaaf** [php-sepa-xml/php-sepa-xml#69]
When using the CustomerCreditFacade the debtorAgentBIC and the creditorBic parameters are required.
Shouldn't this be optional?

**Comment by monofone** [comment]
What pain format do you want to create, probably it depends ?

**Comment by Abdaaf** [comment]
001.001.03

**Comment by monofone** [comment]
At least for the 001.001.03 you are right, they are optional.

**Comment by Abdaaf** [comment]
Now I just leave them empty and they will be overridden by the bank system.

**Comment by monofone** [comment]
I can't find any place in the facade where the `debtorAgentBIC` is required, can you tell me what error do you get ?

**Comment by Abdaaf** [comment]
`
$customerCredit->addPaymentInfo($id, [
            'id'                => '1234',
            'debtorName'        => 'debtor',
            'debtorAccountIBAN' => 'SAMPLEIBAN1234',
            'debtorAgentBIC'    => ''
        ]);
`

So now i leave the BIC empty but if i remove the debtorAgentBIC from the array I get the error: Undefined index: debtorAgentBIC

**Comment by monofone** [comment]
Do you mean `CustomerCreditFacade` ? I'll take a look on this

**Comment by Abdaaf** [comment]
This is how I make my file.

`
$customerCredit = TransferFileFacadeFactory::createCustomerCredit(
            $id,
            $name,
            'pain.001.001.03'
        );
`

**Comment by monofone** [comment]
I can't reproduce your described error, can you provide a little testcase ? And does the generated XML validates against the XSD provided in the test dir ?

**Comment by Abdaaf** [comment]
There was 1 error:

1) tests\CustomerCreditValidationPain00100103Test::testSanity
DOMDocument::schemaValidate(): Element '{urn:iso:std:iso:20022:tech:xsd:pain.001.001.03}BIC': [facet 'pattern'] The value '' is not accepted by the pattern '[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]([A-Z0-9]{3,3}){0,1}'.

In my generated XML the part where the bic is looks like this:
`<DbtrAgt>
<FinInstnId>
<BIC></BIC>
</FinInstnId>
</DbtrAgt>`
