### ISSUE TITLE
CreDtTm bad string length

### ISSUE THREAD

**Issue by davidromani** [php-sepa-xml/php-sepa-xml#70]
Hello.

I've checked my XML output and I'm getting this value for CreDtTm tag

```xml
<CreDtTm>2018-08-28T17:36:22Z</CreDtTm>
```

I think that the right output must be without the latest character (Z) because this tag only allows 19 characters length. Maybe you need to relace the line https://github.com/php-sepa-xml/php-sepa-xml/blob/8f9814bc7c97eda669e93848df3dcdb28ca7debb/lib/Digitick/Sepa/GroupHeader.php#L85 by

```php
protected $creationDateTimeFormat = 'Y-m-d\TH:i:s';
```

**Comment by monofone** [comment]
The 19 Characters are the required ones: YYYY-MM-DDThh:mm:ss but additional characters are allowed it is possible to add fractal seconds with `.5` or a Timezone written as `Z` or also as time difference `-6:00`. Also explained here http://books.xmlschemata.org/relaxng/ch19-77049.html
