### ISSUE TITLE
[PAIN.008.001.02] Dutch validation issues

### ISSUE THREAD

**Issue by barryvdh** [php-sepa-xml/php-sepa-xml#72]
Here is a list of issues I've encountered. This can be handled on our side, but perhaps good to enforce.

 - IBAN needs to be uppercase (and valid)
 - Description (and perhaps other fields) should be max 140 chars
 - (BIC is optional)

**Comment by monofone** [comment]
We had this discussion more often. Should this Lib validate something, os is this application level stuff. I think this library should print valid xml defined by the pain format. The valid content should be delivered by application code.

But there are two places in which we already do validation / transformation and another one where calculation is done. 

These places should be cleaned up and another package should take care about this, enforce valid lengths, valid characters and all the other stuff.

But can you tell how you pass you data to the bank ? which bank it is ? what pain format ?

**Comment by barryvdh** [comment]
See the format in the title. Yeah problem was ING which just fails without clear errors. So if errors would be thrown when outputting, or we could call validate or something on the result, it would be more reliable and prevent lots of checking.

**Comment by monofone** [comment]
Oh yes, the letters were too big :-) 

As I said the validation should reside in the Input Pipeline for the data, so when creating the PamentInformation or TransferInformations. And this is something, I think, another part of the Library should handle. One Idea is to implement a Validator which could just like the XmlBuilder walk through the structure and validate each field. Probably the XSD could help as Input to create the validation rules. 

Just as an Idea, can't you validate the resulting XML against the containing XSD, or even better against an XSD the ING provides ?

Wha did you used to transfer the file to ING ?

**Comment by barryvdh** [comment]
I used the provided xsd from your test site which worked indeed, gave me the same results as the Rabobank validator (don't have one for ING). But as the xsd already here, could be easy to create a class that validates the data, inside this library.

**Comment by monofone** [comment]
One can write a simple wrapper around DOMDocument::loadXML to validate the result as done in the tests.

Can you outline what you used to transfer the XML to the institute ?

**Comment by monofone** [comment]
As there are no real issues with the lib I'll close this, thx for your input
