### ISSUE TITLE
PHP 5.1

### ISSUE THREAD

**Issue by guillermoizqgar** [php-sepa-xml/php-sepa-xml#79]
Is it possible to use it with php 5.1? I can't update the php version right now on this server. Thanks!

**Comment by monofone** [comment]
thx for using this lib, but I'm really unsure if this library ever worked on PHP 5.1, I will drop PHP 5.6 support too in some time as this is already EOL.

**Comment by BorislavSabev** [comment]
@guillermoizqgar php-sepa-xml/php-sepa-xml was originally forked off Digitick/SEPA-xml or something like that. You must upgrade the code and version - it is quite easy to do so with automated scan tools for version compatibility.

One of my projects used to be stuck in PHP 5.2 a few years ago and I had to produce a PHP5.2 version of that:
[Digitick.zip](https://github.com/php-sepa-xml/php-sepa-xml/files/2899423/Digitick.zip)
**Provided as is and with no documenation**


@monofone  I hope it is OK posting this code here - after all we should all help each other.

**Comment by monofone** [comment]
@BorislavSabev sure this is ok, beside that, one should not stay too much behind the current development to prevent security issues by using too old software stacks
