### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by niklasbeinghaus** [php-sepa-xml/php-sepa-xml#80]
Hi,

we're using the php-sepa-xml library via composer and need to use the changes which were merged into master within the commit [dev-master#2a8502dc932b359d632a0cce3671455ab6dc4691](https://github.com/php-sepa-xml/php-sepa-xml/commit/2a8502dc932b359d632a0cce3671455ab6dc4691)

We would like to switch to a tagged release and thus are in need of a version bump. Could somebody please tag a new version (i.e. 1.4.1)?

We're waiting since 11/18 already, **six months** should be more than enough waiting time...

Best,
Niklas

**Comment by monofone** [comment]
stay friendly and patient, I have a new version released
