### ISSUE TITLE
Batch Booking

### ISSUE THREAD

**Issue by ouraios** [php-sepa-xml/php-sepa-xml#81]
Hello,

From what i saw from the package sources i'm not able to set the batchBooking, is this wanted or just a forgot features to be set in the payment information ?

Thanks in advance for your response and thank you for this great package you made !

**Comment by monofone** [comment]
Hi,

if you can point me to the right direction I will gladly improve this and implement this feature

**Comment by monofone** [comment]
this is already implemented, https://github.com/php-sepa-xml/php-sepa-xml/blob/02243489216e130bacc97f8e8a7bfc3a102b0582/lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php#L72

If you set it to true in https://github.com/php-sepa-xml/php-sepa-xml/blob/master/lib/Digitick/Sepa/PaymentInformation.php#L500 this should already work

**Comment by ouraios** [comment]
Here you go 
#82

**Comment by monofone** [comment]
ah, just in the facade, ok, have missed this ...

**Comment by ouraios** [comment]
Yeah just in the facade, i prefer to integrate it that way so it can be easier to use with only using the facade 👍

**Comment by monofone** [comment]
thx for your contribution

**Comment by ouraios** [comment]
You plan to make a 1.6.0 release ?
