### ISSUE TITLE
Method for calculating amounts without requiring bcmath

### ISSUE THREAD

**Issue by vidorado** [php-sepa-xml/php-sepa-xml#84]
With a regular expression we can **calculate amounts without requiring bcmath** library:

This is how the constructor of BaseTransferInformation.php looks after my modification:

**/lib/Digitick/Sepa/TransferInformation/BaseTransferInformation.php**
```php
 public function __construct($amount, $iban, $name)
    {
        if(preg_match("#^([0-9]+)\.([0-9]+)$#", $amount, $matches)) {
          $amount = $matches[1].substr($matches[2],0,2);
        }

        $amount += 0;

        $this->transferAmount = $amount;
        $this->iban = $iban;
        $this->name = StringHelper::sanitizeString($name);
    }
```

**Comment by BorislavSabev** [comment]
Sure it works, but what the point here? Just to remove the dependency on bcmath?
IMHO the library internally works in cents anyhow.

**Comment by vidorado** [comment]
Hi!

I had to use it in a server without bcmath installed and no possibility of
installing it, that was the point!

**Comment by monofone** [comment]
I Like the idea to get rid if this lib, beside this I would like to remove the support for floats fully, but this is on another story.

If someone could craft a PR with tests for this I will be happy to merge this.

**Comment by VincentLanglet** [comment]
@monofone I think you can close this issue since you're dropping the float support
