### ISSUE TITLE
Impossible to add PstlAdr in format pain.008.001.02

### ISSUE THREAD

**Issue by bberjawi** [php-sepa-xml/php-sepa-xml#88]
It is impossible to add PstlAdr for debit with format pain.008.001.02
in CustomerDirectDebitTransferDomBuilder L171 :
if (in_array($this->painFormat, array('pain.008.003.02'))) { $addPostalAddress = false; $postalAddress = $this->createElement('PstlAdr');

The PstlAdr is allowed in format 008.001.02 (check https://businessbanking.bankofireland.com/app/uploads/2016/07/SEPA-Direct-Debit-PAIN.008.001.02-XML-File-Structure-PDF.pdf)

**Comment by monofone** [comment]
should be fixed with this new release 1.6.2, if there are any issues don't mind to open a new issue
