### ISSUE TITLE
Debitor name and end-to-end id not sanitized

### ISSUE THREAD

**Issue by reikjarloekl** [php-sepa-xml/php-sepa-xml#90]
I just noticed, that the debitor name and end-to-end ID are currently not sanitized. This created an issue in the software I am using the library in because a bank rejected the XML due to an ampersand in the debitor name "GmbH & Co. KG".

Is the debitor name and end-to-end-id not sanitized on purpose currently? If not, this should IMHO be added. Happy to contribute a PR - let me know.

**Comment by reikjarloekl** [comment]
Hmm, sorry - just noticed that according to Code they actually **are** sanitized. However, I am still ending up with the ampersands in both name and end-to-end-id... Will investigate.

**Comment by monofone** [comment]
Probably the test does not catch a glitch in the regex https://github.com/php-sepa-xml/php-sepa-xml/blob/460072d2804c26d0b80da02fecd304e587e6c2b1/tests/Unit/Digitick/Sepa/Util/StringHelperTest.php#L26

**Comment by reikjarloekl** [comment]
Thanks for the quick answer - and sorry for any confusion caused. I currently cannot reproduce the problem anymore. I forked the repo and extended the test case with an ampersand but it passes just fine. Also added a sanitization test to `CustomerDirectDebitTransferInformationTest` and it passes as well as expected.

The issue occurred on a customers site that I don't have direct access to so I have to trust the customers claims regarding versions used etc. Will close the issue for now and investigate further any other possible causes (old versions used, manipulation of XML after creation, ...)

Sorry again.
