### ISSUE TITLE
[Question] Schema pain.008.002.02 is inofficial?

### ISSUE THREAD

**Issue by naitsirch** [php-sepa-xml/php-sepa-xml#91]
I wanted to know some more details about _pain.008.002.02_ that is used by this library, but I could not find anything about it on the official site https://www.iso20022.org/. So I asked them were I could find these information. The response I got was:

> The answer to your question is rather simple. You don’t find pain.008.002.02 in the Catalogue of messages because it is not an official ISO 20022 message.
> 
> All latest versions of the ISO 20022 messages are published in the Catalogue of ISO 20022 messages and previous version on the Archive page: https://www.iso20022.org/message_archive.page

Now I am just curious where this _pain.008.002.02_ comes from and whether it makes sense to deprecate it and support the newer _pain.008.001.0x_ (at the moment it is _pain.008.001.08_) schema versions?

**Comment by monofone** [comment]
It might be that pain.008.002.02 is not an ISO standard, but someone found an xsd for it, implemented it and it seems that it is in use by some people. So why throw it away.

At the moment there is already support for the newer schema, and no one requested support for the versions you mentioned.

I'm curious how do you transfer you xml files to the bank ? I`m still looking for some gateway support to banks here in europe.

**Comment by naitsirch** [comment]
> It might be that pain.008.002.02 is not an ISO standard, but someone found an xsd for it, implemented it and it seems that it is in use by some people.

Okay, thanks for clarification :-)
We are using it too, because this schema was used in the examples of this project and it worked. It's just that I wanted to know whether it is the "right" way.

> I'm curious how do you transfer you xml files to the bank ? I`m still looking for some gateway support to banks here in europe.

Our accounting department manually uploads the xml files in the backend of our bank (Commerzbank, Germany). This is okay for us.
