### ISSUE TITLE
Make sure that a PaymentInfo contains at least one Transfer

### ISSUE THREAD

**Issue by stollr** [php-sepa-xml/php-sepa-xml#92]
If there are PaymentInfo elements that do not contain any Transfer the generated XML is invalid. At least in `pain.008.002.02` that is the case.

It would increase the developer experience if an exception is thrown if there is an empty PaymentInfo, when the XML is generated.

**Comment by monofone** [comment]
Hehe, you already opened an issue mentioning the same pain format. Are you using it somehow ?

**Comment by naitsirch** [comment]
Yes, we are using it and it is supported by our bank (Commerzbank).

**Comment by BorislavSabev** [comment]
@stollr I don't think this is in scope of the library per say. This is an application problem for me. 

To solve it in your application you can add a post-generation step and validate the resulting XML file against the XSDs available over at iso20022.org . You can use `DomDocument` for that.
