### ISSUE TITLE
Question about receiver bic

### ISSUE THREAD

**Issue by grazianodimaio** [php-sepa-xml/php-sepa-xml#94]
Hello,
thanks for this awesome library.

One question:

Is the BIC value for the receiver mandatory or i can create the payment without having it ?

**Comment by monofone** [comment]
I'think it is not mandatory but at a first glance I didn't found something. Just give it a try and answer here ;-)

**Comment by mogilvie** [comment]
BIC is not mandatory with a valid IBAN.
