### ISSUE TITLE
Payment Info CIF/NIF (id) Required

### ISSUE THREAD

**Issue by oskar-jj** [php-sepa-xml/php-sepa-xml#98]
Hi,

I did test to generate a pain.001.001.03 pyment file but when I upload the file to the bank account, the bank tells taht the Dbtr has to include the NIF/CIF information.

I did create the same payment with the bank tool (this is spanish bank) and here are the differences.
With your code:

```
      <Dbtr>
        <Nm>SOCIAL </Nm>
      </Dbtr>
      <DbtrAcct>
        <Id>
          <IBAN>ES03xxxxxxxxxxxxxxxxx</IBAN>
        </Id>
        <Ccy>EUR</Ccy>
      </DbtrAcct>
      <DbtrAgt>
        <FinInstnId>
          <BIC>BSxxxxxxxxxxxxx</BIC>
        </FinInstnId>
      </DbtrAgt>
```

and with the bank file it adds the

   ```
  <Dbtr>
            <Nm>SOCIAL </Nm>
            **<Id>
               <OrgId>
                  <Othr>
                     <Id>Bxxxxxxxx0000</Id>
                  </Othr>
               </OrgId>
            </Id>**
         </Dbtr>
         <DbtrAcct>
            <Id>
               <IBAN>ES0300810036410002757382</IBAN>
            </Id>
            <Ccy>EUR</Ccy>
         </DbtrAcct>
         <DbtrAgt>
            <FinInstnId>
               <BIC>BSABESBBXXX</BIC>
            </FinInstnId>
         </DbtrAgt>

```

How I can add to the Payment info this OrgId ?

Thanks a lot.

Rgds,

**Comment by monofone** [comment]
You need to call `setOriginBankPartyIdentification(<yourId>)` on the PaymentInformation. It is not exposed via the Facades so you need to create the paymentinformation  "by hand"

**Comment by monofone** [comment]
Don't hesitate to reopen this issue when something does not work for you.
